### Site metadata

# Don't make the title longer than this, otherwise it gets covered in mobile view.
title: Muhammad's Blog
description: Static blog - built with Jekyll and GitHub Pages

email: muhammad.jazman@gmail.com
twitter_username:
github_username: muhammadjazman
rss: RSS

### Build settings

url: https://muhammadjazman.github.io
baseurl: /

permalink: pretty

theme: minima

plugins:
  - jekyll-feed
  - jekyll-sitemap

collections:
  tools:
    output: true
  languages:
    output: true

defaults:
  - scope:
      path: ""
    values:
      layout: page

exclude:
  - docs/
  - vendor/
  - Gemfile # Gemfile.lock is implied because of how matching works.
  - LICENSE
  - Makefile
  - README.md
  - sample*.png

liquid:
  error_mode: strict

strict_front_matter: true
